# Generated by Django 5.0.6 on 2024-06-06 23:52

import Sensores.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antebrazo', models.CharField(max_length=50)),
                ('base', models.CharField(max_length=50)),
                ('brazo', models.CharField(max_length=50)),
                ('muñeca', models.CharField(max_length=50)),
                ('pinza', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[(Sensores.models.Estado['APAGADO'], 'Apagado'), (Sensores.models.Estado['ENCENDIDO'], 'Encendido')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('ejex', models.IntegerField()),
                ('ejey', models.IntegerField()),
                ('ejez', models.IntegerField()),
                ('brazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Sensores.brazo')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaControladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPines', models.IntegerField()),
                ('brazo_robotico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placa_controladora', to='Sensores.brazo')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloBluetooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(Sensores.models.Estado['APAGADO'], 'Apagado'), (Sensores.models.Estado['ENCENDIDO'], 'Encendido')], max_length=10)),
                ('placa_controladora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='Sensores.placacontroladora')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadax', models.IntegerField()),
                ('coordenaday', models.IntegerField()),
                ('coordenadaz', models.IntegerField()),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='Sensores.movimiento')),
            ],
        ),
    ]
